### ISSUE TITLE
Demo server out of memory

### ISSUE THREAD

**Issue by fnogatz** [SWI-Prolog/pengines#11]
The [scratchpad demo server](http://pengines.swi-prolog.org/apps/scratchpad/index.html#) isn't working anymore:

> Service Unavailable Not enough resources: no_memory In: [13] thread_create(wrap_spawned((0x7f5c4c86ea90),...),69,[...]) [12] thread_httpd:http_spawn(http_dispatch: ...,[]) at /usr/lib/swi-prolog/library/http/thread_httpd.pl:796 [8]

![screenshot from 2015-06-01 23 16 26](https://cloud.githubusercontent.com/assets/881988/7923568/7ccf0bf0-08b4-11e5-8402-a34f521d8b2e.png)

**Comment by JanWielemaker** [comment]
Thanks.  Restarted
