### ISSUE TITLE
http://pengines.swi-prolog.org/ internal error

### ISSUE THREAD

**Issue by orencio** [SWI-Prolog/pengines#25]
The pengine site http://pengines.swi-prolog.org/ is defunct with this error:
> ## Internal server error
> I/O error in write on stream <stream>(0x7f1958025f60) (Disk quota exceeded)
> In:
> [12] format(<stream>(0x7f1958025f60),'/*~s*/ request(~q, ~3f, ~q).~n',["Mon Jul 16 14:03:40 2018",235850|...])
> [9] broadcast:broadcast('<garbage_collected>') at /usr/lib/swi-prolog/library/broadcast.pl:123
> [8] httpd_wrapper:call_handler(http_unix_daemon:http_dispatch,235850,'<garbage_collected>') at /usr/lib/swi-prolog/library/http/http_wrapper.pl:319
> [7] catch(httpd_wrapper:call_handler(...,235850,...),error(io_error(write,<stream>(0x7f1958025f60)),context(...,'Disk quota exceeded')),httpd_wrapper:true) at /usr/lib/swi-prolog/boot/init.pl:372
> [6] httpd_wrapper:handler_with_output_to(http_unix_daemon:http_dispatch,235850,'<garbage_collected>',current_output,error(io_error(write,<stream>(0x7f1958025f60)),context(...,'Disk quota exceeded'))) at /usr/lib/swi-prolog/library/http/http_wrapper.pl:297
> [5] httpd_wrapper:handler_with_output_to('<garbage_collected>',235850,'<garbage_collected>',<stream>(0x7f1938283430),error(io_error(write,<stream>(0x7f1958025f60)),context(...,'Disk quota exceeded'))) at /usr/lib/swi-prolog/library/http/http_wrapper.pl:309
> 
> Note: some frames are missing due to last-call optimization.
> Re-run your program in debug mode (:- debug.) to get more detail.
> SWI-Prolog httpd at pengines

**Comment by JanWielemaker** [comment]
Thanks.  Should be fine.  Note that pengines is getting old.  For interactive use use swish.swi-prolog.org.
Tobjron is working on a new version of web-enabled Prolog.
