### ISSUE TITLE
Does pengines support DCG?

### ISSUE THREAD

**Issue by tpalayda** [SWI-Prolog/pengines#27]
I have imported DCG library into my main prolog file, though i get "error:"instantiated_error", data:"Sandbox restriction". (i'm thinking it's because of using ```-->``` from DCG).

Does pengines recognize ```--> ``` from DCG?

**Comment by JanWielemaker** [comment]
DCGs are fine.  See e.g., https://swish.swi-prolog.org/example/grammar.pl

Please use the forum for questions.  You can use the public swish to reproduce your problem.
