### ISSUE TITLE
Error: Refusing to run HTTP server as root: No permission to open server `http`

### ISSUE THREAD

**Issue by ufnalbartosz** [SWI-Prolog/pengines#28]
I'm getting the `Refusing to run HTTP server as root: No permission to open server http` after I downloaded and run the `swipl ./daemon.pl --port=3030 --fork=false` command.

```
:~# uswipl --version
SWI-Prolog version 8.5.2 for x86_64-linux
```

**Comment by JanWielemaker** [comment]
For security reasons the HTTP daemon framework refuses to run as root.   It you start it as root, add a `--user=someuser` option.

**Comment by ufnalbartosz** [comment]
Thanks for the answer!
